# Generated by Django 2.2.24 on 2023-05-17 19:36

from django.db import migrations


def set_new_building_value(apps, schema_editor):
    ModelName = apps.get_model('property', 'Flat')
    ModelName.objects.filter(construction_year__gte=2015).update(new_building=True)
    ModelName.objects.filter(construction_year__lt=2015).update(new_building=False)


def set_old_building_value(apps, schema_editor):
    ModelName = apps.get_model('property', 'Flat')
    ModelName.objects.filter(construction_year__gte=2015).update(new_building=False)
    ModelName.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building_value, reverse_code=set_old_building_value),
    ]
