# Generated by Django 2.2.24 on 2023-05-17 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_compliant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliant',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.Flat', verbose_name='Квартира, на которую пожаловались'),
        ),
        migrations.AlterField(
            model_name='compliant',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст жалобы'),
        ),
        migrations.AlterField(
            model_name='compliant',
            name='user',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
