# Generated by Django 2.2.24 on 2023-05-17 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0006_auto_20230517_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
