# Generated by Django 2.2.24 on 2023-05-17 21:14

from django.db import migrations
import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            normalized_number = phonenumbers.format_number(phone_number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.owner_pure_phone = normalized_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230518_0005'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]
