# Generated by Django 2.2.24 on 2023-05-17 21:14

from django.db import migrations
import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    phone_numbers = Flat.objects.filter(owners_phonenumber__isnull=False)\
                                 .exclude(owner_pure_phone__isnull=False)\
                                 .values_list('owners_phonenumber', flat=True)
    phone_numbers = [phonenumbers.format_number(phonenumbers.parse(number, 'RU'), phonenumbers.PhoneNumberFormat.INTERNATIONAL)
                     for number in phone_numbers]
    flats = Flat.objects.filter(owners_phonenumber__isnull=False)\
                         .exclude(owner_pure_phone__isnull=False)
    flats.update(owner_pure_phone=normalized_numbers)

def reverse_normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.filter(owners_phonenumber__isnull=False, owner_pure_phone_backup__isnull=False)
    flats.update(owner_pure_phone=F('owner_pure_phone_backup'), owner_pure_phone_backup=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230518_0005'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers, reverse_code=reverse_normalize_phone_numbers)
    ]
