# Generated by Django 2.2.24 on 2023-05-18 21:14

from django.db import migrations


def fill_class_owner_from_class_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flat_values = Flat.objects.values('owner', 'owners_phonenumber', 'owner_pure_phone', 'flat')
    owners = [Owner(**flat_value) for flat_value in flat_values]
    Owner.objects.bulk_create(owners)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(fill_class_owner_from_class_flat, reverse_code=migrations.RunPython.noop)
    ]
