# Generated by Django 2.2.24 on 2023-05-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230519_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
