# Generated by Django 2.2.24 on 2023-05-26 19:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0015_auto_20230526_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compliant',
            new_name='Complaint',
        ),
    ]
