# Generated by Django 2.2.24 on 2023-05-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20230526_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flat',
            new_name='flats',
        ),
    ]
