# Generated by Django 2.2.24 on 2023-05-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20230527_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='property.Flat', verbose_name='Квартира в собственности'),
        ),
    ]
