# Generated by Django 2.2.24 on 2023-05-27 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20230527_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
