# Generated by Django 2.2.24 on 2023-05-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20230527_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
